version: "3.8"
services:
  service:
    build:
      context: .
      target: dev
      dockerfile: ./Dockerfile
    image: ${PRODUCT}/${SERVICE}:${VERSION}d
    container_name: ${SERVICE}
    restart: unless-stopped
    tty: true
    volumes:
      - ./launcher:/app/launcher:ro
      - ./service:/app/service:ro
    scale: 1
    env_file:
      - ./.env
      - ./.env.secrets

networks:
  default:
    name: ${DEV_NETWORK}
    external: true
  
